@startuml
class Paciente {
  -id : int
  -nome : String
  -dataNascimento : Date
  -endereco : String
  -telefone : String
  -telefoneEmergencia : String
}

class FichaTecnica {
  -id : int
  -paciente: int
  -historicoMedico : int
  -medicamentos : int
  -restricoesAlimentares : int
  -procedimentosEspecificos : int
  -observacoes : int
}

  ' Mobilidade: Verificar a capacidade de locomoção. 
  ' Atividades de Vida Diária (AVDs): Avaliar a autonomia para atividades como banho, alimentação, vestir-se e uso do banheiro. 
  ' Atividades Instrumentais de Vida Diária (AIVDs): Avaliar a capacidade de gerir o lar, como fazer compras, usar o telefone, gerenciar finanças. 
  ' Presença de Cuidador: Se sim, especificar a jornada e as funções do cuidador. 

class tipoHistoricoMedico {
  -id : int
  -descricao : String
}

  ' Doenças atuais e pregressas, Cirurgias, Alergias, Histórico familiar

class historicoMedico {
  -id : int
  -id_ficha: int
  -tipo: int
  -descricao : String
}

class Medicamento {
  -id : int
  -id_ficha: int
  -nome : String
  -dosagem : String
  -frequencia : String
  -viaAdministracao : String
  -inicioTratamento : Date
  -fimTratamento : Date
}

class RestricaoAlimentar {
  -id : int
  -id_ficha: int
  -descricao : String
}

class ProcedimentoEspecifico {
  -id : int
  -id_ficha: int
  -id_procedimento : String
  -horarios : String
  -descricao : String
}

class Procedimento {
  -id : int
  -id_ficha: int
  -nome : String
}

class Documento {
  -id : int
  -tipo : int
  -paciente: int
  -descricao : String
  -arquivo : File
}

class Agenda {
  -id : int
  -data : Date
  -atividade : String
  -paciente: int
}

class RelatorioDiario {
  -id : int
  -paciente: int
  -data : Date
  -conteudo : String
}

class Observacao {
  -id : int
  -texto : String
  -data : Date
  -familiar: int
}

class Cuidador {
  -id : int
  -nome : String
  -email : String
  -senha : String
  +cadastrarPaciente()
  +editarFichaTecnica()
  +editarAgenda()
  +editarRelatorio()
  +anexarDocumento()
  +visualizarObservacoes()
}

class Familiar {
  -id : int
  -nome : String
  -email : String
  -senha : String
  -paciente: int
  +visualizarAgenda()
  +visualizarDocumentos()
  +visualizarFichaTecnica()
  +visualizarRelatorio()
  +cadastrarObservacao()
}

' -----------------------------
' RELACIONAMENTOS
' -----------------------------
Paciente "1" -- "1" FichaTecnica
Paciente "1" -- "*" Documento
Paciente "1" -- "*" Agenda
Paciente "1" -- "*" RelatorioDiario
Paciente "1" -- "*" Observacao
Paciente "1" -- "*" Familiar

FichaTecnica "1" -- "*" historicoMedico
historicoMedico "*" -- "1" tipoHistoricoMedico
FichaTecnica "1" -- "*" Medicamento
FichaTecnica "1" -- "*" RestricaoAlimentar
FichaTecnica "1" -- "*" ProcedimentoEspecifico
ProcedimentoEspecifico "*" -- "1" Procedimento
FichaTecnica "1" -- "*" Observacao

Cuidador "1" -- "*" Paciente
Familiar "1" -- "1" Paciente
@enduml