@startuml
actor Cuidador

participant "Sistema" as Sistema
database "Banco de Dados" as BD

Cuidador -> Sistema : Solicitar cadastro de paciente
Sistema -> Cuidador : Exibir formulário de cadastro
Cuidador -> Sistema : Preencher e enviar dados do paciente
Sistema -> Sistema : Validar dados do paciente
alt Dados válidos
    Sistema -> BD : Inserir novo paciente
    BD --> Sistema : Confirma inserção
    Sistema -> Cuidador : Cadastro realizado com sucesso
else Dados inválidos
    Sistema -> Cuidador : Exibir mensagem de erro
end

@enduml
